# Generated by Django 6.0.1 on 2026-01-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='P2POrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=64)),
                ('nickname', models.CharField(max_length=255)),
                ('crypto', models.CharField(max_length=10)),
                ('fiat', models.CharField(max_length=10)),
                ('trade_type', models.CharField(max_length=4)),
                ('price', models.DecimalField(decimal_places=8, max_digits=18)),
                ('available', models.DecimalField(decimal_places=8, max_digits=18)),
                ('min_amount', models.DecimalField(decimal_places=8, max_digits=18)),
                ('max_amount', models.DecimalField(decimal_places=8, max_digits=18)),
                ('payment_methods', models.TextField()),
                ('completed_orders', models.IntegerField()),
                ('completion_rate', models.CharField(max_length=10)),
                ('is_merchant', models.BooleanField()),
                ('is_online', models.BooleanField()),
                ('last_online', models.CharField(max_length=32)),
                ('order_amount_crypto', models.DecimalField(decimal_places=8, max_digits=18)),
                ('order_amount_fiat', models.DecimalField(decimal_places=8, max_digits=18)),
                ('parsed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['crypto', 'fiat', 'trade_type'], name='parse_p2por_crypto_1863af_idx')],
            },
        ),
    ]
