# Generated by Django 6.0.1 on 2026-01-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse', '0002_p2porder_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='p2porder',
            name='available',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='p2porder',
            name='completed_orders',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='p2porder',
            name='completion_rate',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='p2porder',
            name='is_online',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='p2porder',
            name='last_online',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='p2porder',
            name='max_amount',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='p2porder',
            name='min_amount',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='p2porder',
            name='order_amount_crypto',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='p2porder',
            name='order_amount_fiat',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True),
        ),
    ]
