# Generated by Django 6.0.1 on 2026-01-26 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parse', '0003_alter_p2porder_available_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='P2POrderBuy',
            fields=[
            ],
            options={
                'verbose_name': 'P2POrder BUY',
                'verbose_name_plural': 'P2POrder BUY',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('parse.p2porder',),
        ),
        migrations.CreateModel(
            name='P2POrderSell',
            fields=[
            ],
            options={
                'verbose_name': 'P2POrder SELL',
                'verbose_name_plural': 'P2POrder SELL',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('parse.p2porder',),
        ),
    ]
