# Generated by Django 4.2.11 on 2026-02-12 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse', '0005_alter_p2porder_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='p2porder',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
